### ISSUE TITLE
[Documentation] Tutorial of environment setup 

### ISSUE THREAD

**Issue by MXMX0811** [shinolab/autd3-old-monorepo#133]
If the part of the installation of Vulkan SDK is still necessary in the current version?

**Comment by s5suzuki** [comment]
No. So, I think I deleted it from the documents. Is it still there somewhere?

**Comment by MXMX0811** [comment]
If so, there's no more problem. Sun-san met the Vulkan SDK unexist when he was configuring the environment, and I checked his environment found that he was using old version. So I just want to confirm if it is still necessary.
