### ISSUE TITLE
`protobuf` is needed when run `cargo build` on Windows

### ISSUE THREAD

**Issue by MXMX0811** [shinolab/autd3-old-monorepo#136]
Is it necessary to add it to the tutorial?

**Comment by s5suzuki** [comment]
You should not need protobuf compiler to build the code in the tutorial, at least. (Also, README of each library which depends on it has already mentioned that protobuf is required.)

**Comment by s5suzuki** [comment]
However, it might be a good idea to add this to each Link and Simulator chapter of the documentation.

**Comment by MXMX0811** [comment]
Ah, sorry, I only searched protobuf in the tutorial and missed checking the README of each library.
