### ISSUE TITLE
`ninja` is needed when build cpp examples on Windows

### ISSUE THREAD

**Issue by MXMX0811** [shinolab/autd3-old-monorepo#137]

**Comment by s5suzuki** [comment]
Ninja must not be needed to build C++ samples. C++ version library only depends on Eigen3 which is header-only and should not require any build system.

**Comment by MXMX0811** [comment]
I met this error when I built the cpp examples following the README in the cpp directory using build.ps1.

**Comment by s5suzuki** [comment]
Ah, yes, README is wrong. You don't need to run `build.ps1`. Also, `AUTD_LOCAL_TEST` flag is not required.
