### ISSUE TITLE
`fatal runtime error: Rust panics must be rethrown` when get the firmware information

### ISSUE THREAD

**Issue by MXMX0811** [shinolab/autd3-old-monorepo#162]
When I used TwinCAT on a Windows PC and use `print("\n".join([str(firm) for firm in autd.firmware_info_list()]))` to get the firmware information, I have this:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', autd3capi\src\lib.rs:154:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
```

**Comment by s5suzuki** [comment]
Probably, You are usign old firmware or an old AUTD Server.
Please use the latest version.

**Comment by MXMX0811** [comment]
OK, I will check it later, but I remember that I have updated it to the new version corresponding to v15.1.1 and SOEM can work well...

**Comment by s5suzuki** [comment]
Please check the following:
1. firmware version is v3.0.2 when using SOEM
1. the version displayed in the title bar of AUTD Server is v15.1.1
1. Lightweight mode is off in AUTD Server
