### ISSUE TITLE
`pyautd3.autd_error.AUTDError: Read firmware info failed`

### ISSUE THREAD

**Issue by MXMX0811** [shinolab/autd3-old-monorepo#174]
After connecting to AUTDs using TwinCAT server, I have this when I run a program:

```
Traceback (most recent call last):
  File "c:\Users\Zhang\Documents\Zhang\Surface-Rendering\texture_rendering\SLS-3waves.py", line 159, in run
    firm_info_list = autd.firmware_info_list()
  File "C:\Users\Zhang\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautd3\autd.py", line 199, in firmware_info_list
    raise AUTDError(err)
pyautd3.autd_error.AUTDError: Read firmware info failed: 0, 1, 2, 3
```

The firmware version is 3.0.2 and the pyautd3 is newly built from the newest source code. The server version is v15.1.1.

**Comment by s5suzuki** [comment]
Let me see TwinCAT screenshot, as follows, open "SYSTEM"→"Task"→"Task 1"→"Output", please.
![2023-09-22 072657](https://github.com/shinolab/autd3/assets/28915329/e7460739-7198-4fdb-b4cc-3045d9ce326c)

**Comment by s5suzuki** [comment]
@ZhangMingxin1997 is there any progress?

**Comment by MXMX0811** [comment]
Sorry, these days I am mainly writing the paper... I will check it this afternoon. 🙇‍♂️

**Comment by MXMX0811** [comment]
![Output](https://github.com/shinolab/autd3/assets/39915426/a88967ea-5685-42fa-b630-0addbf25c622)

This is the output.

**Comment by s5suzuki** [comment]
As shown in the error message, there is something wrong with the communication between the second and the fourth AUTD3 device.
Please make sure that the Ethernet cables between the 2nd-3rd and 3rd-4th devices are of CAT5e or better. Also check if the order of In/Out ports is correct.
(SOEM is loose, so it may work even if these are wrong.)
