### ISSUE TITLE
[documentation] Typo in a CMaske code block in the tutorial document

### ISSUE THREAD

**Issue by YutaItoh** [shinolab/autd3-old-monorepo#21]
In a sample tutorial document,
https://github.com/shinolab/autd3/blob/master/book/src/jp/Software/Users_Manual/getting_started.md
, a CMake-style sample code block contains an escaped `\$` instead of just `$`, which causes an error when copying and pasting it to a local code for the tutorial:
https://github.com/shinolab/autd3/blame/4a8d8b3147fb745e5091853a7ea3e731900f3ee5/book/src/jp/Software/Users_Manual/getting_started.md#L117

**Comment by s5suzuki** [comment]
This markdown is not intended to be displayed on Github.
This document source is compiled by mdbook, and the document is available on the following GitHub Pages.
https://shinolab.github.io/autd3/book/jp/Software/Users_Manual/getting_started.html
In the above site, the escaped symbol should be displayed without problems, and copy/paste work correctly.
