### ISSUE TITLE
[documentation] Deprecated method called in a C++ code block in the tutorial document

### ISSUE THREAD

**Issue by YutaItoh** [shinolab/autd3-old-monorepo#22]
In a sample tutorial document,
https://github.com/shinolab/autd3/blob/master/book/src/jp/Software/Users_Manual/getting_started.md
a C++ code block has this API call:
` autd.check_ack = true;`
which is likely to be
`  autd.check_trials = 50;`
to correctly being compiled with a recent autd3 release version since 2.2.1 according to:
https://github.com/shinolab/autd3/blob/11fceddba40153061517ca681876bbd701ef8f67/CHANGELOG.md#221

Blamed line:
https://github.com/shinolab/autd3/blame/94b2963f01117b4d527b84d71f6d746fc0405269/book/src/jp/Software/Users_Manual/getting_started.md#L155

**Comment by s5suzuki** [comment]
The document may be updated independently of the master branch.
Please check the following page for the latest document.
https://shinolab.github.io/autd3/book/jp/Software/Users_Manual/getting_started.html
